name: shopeefood_local
description: A local-only ShopeeFood-like app for kuliah assignment
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  icons_plus: ^5.0.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.2
  image_picker: ^1.1.1
  path_provider: ^2.1.1 
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.6.0


flutter:
  assets:
    - assets/images/es_teh.jpg
    - assets/images/mie_ayam.jpg
    - assets/images/nasi_goreng.jpg
    - assets/images/ayam_geprek.jpg
    - assets/images/burger.jpg
    - assets/images/mcd.jpg
    - assets/images/kentang.jpg
    - assets/images/pizza.jpg
    - assets/images/pizza_hut.jpg
    - assets/images/starbucks.jpg
    - assets/images/sushi_tei.jpg
  uses-material-design: true
